name: CI
on: [push, pull_request]
env:
  UI_VERSION: ${{ github.sha }}
jobs:
  build:
    name: Build & test
    runs-on: ubuntu-latest
    container: httptoolkit/act-build-base:v3.0.0
    steps:
      - uses: actions/checkout@v3

      # Install Node
      - uses: actions/setup-node@v3
        with:
          node-version: 20.8.0
          cache: 'npm'

      - run: npm install -g npm@8.5.5

      # Install & build & test:
      - run: npm ci
      - run: npm run build

      - uses: actions/upload-artifact@v3
        with:
          name: dist
          path: dist/*
          if-no-files-found: error

  publish-netlify:
    name: Deploy ${{ (github.ref == 'refs/heads/main' && 'to Netlify production') || 'Netlify preview' }}
    if: github.event_name == 'push'
    runs-on: ubuntu-latest
    container: httptoolkit/act-build-base
    needs: build
    steps:
      - uses: actions/checkout@v3

      - uses: actions/download-artifact@v3
        with:
          name: dist
          path: dist

      - name: Deploy to Netlify
        uses: nwtgck/actions-netlify@v1.1
        with:
          publish-dir: './dist'
          production-branch: main # Main goes to prod, others do deploy previews
          github-token: ${{ secrets.GITHUB_TOKEN }}
          deploy-message: GHA Deploy - ${{ github.event.head_commit.message }}
          enable-commit-status: true
          enable-pull-request-comment: false
          enable-commit-comment: false
          netlify-config-path: ./netlify.toml
          alias: ${{ github.sha }}
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
        timeout-minutes: 1
